# api-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: digi-api
  template:
    metadata:
      labels:
        app: digi-api
    spec:
      containers:
      - name: api-container
        image: digi_lib_api:latest
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: api-nodeport-service
spec:
  selector:
    app: digi-api
  ports:
    - protocol: TCP
      port: 8082  # The port on the service
      targetPort: 8082  # The port on the pod
  type: NodePort